# Generated by Django 4.2.21 on 2025-06-26 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('attendee', 'Attendee'), ('organizer', 'Organizer')], max_length=20)),
                ('secure_token', models.CharField(default=user_service.models.generate_secure_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_tickets_reserved', models.PositiveIntegerField(default=0)),
                ('deleted_events_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
