# Generated by Django 4.2.21 on 2025-10-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_consent',
            field=models.BooleanField(default=False, help_text='Accepte de recevoir des recommandations par email'),
        ),
    ]
