# Generated by Django 4.2.21 on 2025-10-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_userprofile_email_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_consent',
            field=models.BooleanField(blank=True, default=False, help_text='Accepte de recevoir des recommandations par email', null=True),
        ),
    ]
