# Generated by Django 4.2.21 on 2025-10-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_service', '0004_reservation_ambassador'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='event_service.event')),
            ],
        ),
    ]
