# Generated by Django 4.2.21 on 2025-10-10 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ambassadors',
            field=models.ManyToManyField(blank=True, related_name='ambassador_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
