# Generated by Django 4.2.21 on 2025-10-10 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_service', '0002_reservation_ambassadors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='ambassadors',
        ),
        migrations.AddField(
            model_name='event',
            name='ambassadors',
            field=models.ManyToManyField(blank=True, related_name='ambassador_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
