# Generated by Django 4.2.21 on 2025-10-10 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_service', '0003_remove_reservation_ambassadors_event_ambassadors'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ambassador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassador_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
