# Generated by Django 4.2.21 on 2025-10-11 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_service', '0004_reservation_ambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, help_text="Image de couverture de l'événement (1200x630 recommandé)", null=True, upload_to='event_covers/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ambassador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ambassador_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
