# Generated by Django 4.2.21 on 2025-10-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_service', '0005_event_cover_image_alter_reservation_ambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Commission pour les ambassadeurs (%)', max_digits=5),
        ),
    ]
