# Generated by Django 4.2.21 on 2025-06-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('org_name', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
